/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cxqsyqaofemzrqpswvyz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cXN5cWFvZmVtenJxcHN3dnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzYzNDEsImV4cCI6MjA3MzIxMjM0MX0.MGC-iR4EDoOH5rsRME7Dc3rOd8lLqdy9RKsXoGyAGP4"
